### PR TITLE
Issue #2: Adding the ability to retrieve zone statuses

### PR DESCRIPTION
**Pull request by uchagani**
This PR resolves issue #2 by adding the ability to get the status of all zones in a given location.

### CODE REVIEW

**Comment by uchagani** [comment]
@wardcraigj any chance we can merge this PR?  I have another one ready to go that adds a new alarm code that is missing currently.

**Comment by uchagani** [comment]
Closing this PR.  Will re-open with a clean branch

**Comment by wardcraigj** [comment]
Should be updated as version 0.13 on pypi

**Comment by uchagani** [comment]
🥇

**Comment by uchagani** [comment]
@wardcraigj did you get a chance to bump versions on home assistant?

**Comment by wardcraigj** [comment]
I haven't yet. I can make a PR to bump the client version number now though. I probably won't get a chance to implement the zone sensors for a while though.

**Comment by wardcraigj** [comment]
update pr https://github.com/home-assistant/home-assistant/pull/10610/files

**Comment by uchagani** [comment]
💯 thank you.  I'm trying to update the home assistant client to use the new added state but running into a small issue.  any way we can chat somewhere if you have some time?

**Comment by wardcraigj** [comment]
Yep, are you on the Home Assistant Discord? My username there is Midwinter86

**Comment by kkr16** [comment]
The get_zone_status does not seem to work on my L5100 panel.
I just put in a pull request for get_zone_state https://github.com/wardcraigj/total-connect-client/pull/13
 which is based on GetZonesListInState described on https://rs.alarmnet.com/TC21api/tc2.asmx

With the current polling interval of 30 seconds, I don't think you can capture doors opening or closing events due to their transient nature.
@uchagani, how are you planning to use this?

**Comment by uchagani** [comment]
@kkr16 my biggest use case was to be able to only arm certain zones via the `custom_bypass` arm method

**Comment by kkr16** [comment]
@uchagani did the existing get_zone_status() work for you? If so, what panel do you have?

**Pull request closed without merging**
